# Enter application name as seen on http://appengine.google.com
application: appnamehere
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: src/css

- url: /js
  static_dir: src/js

- url: /images
  static_dir: src/images

- url: /.*
  script: app.app

libraries:
- name: jinja2
  version: latest
